### users test
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "test6",
    "email": "test6@example.com",
    "password": "test6",
    "first_name": "test6",
    "last_name": "test6",
    "address": "test6",
    "role": "USER"
}

###
DELETE http://localhost:3000/api/users/696bc23131cc181ac0e8bef6


###
PUT http://localhost:3000/api/users/696bc23131cc181ac0e8bef6
Content-Type: application/json

{
    "address": "test6-updated"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "test6@example.com",
    "password": "test6"
}

### products test
GET http://localhost:3000/api/products

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Test Barbara1",
    "description": "Delicious barbara1 chocolate",
    "price": 5.99,
    "stock": 50,
    "category": "chocolate"
}

###
GET http://localhost:3000/api/products/696897940f34cb9f5d50c48f

###
PUT http://localhost:3000/api/products/696e7878dc53bb780fcc29b7
Content-Type: application/json

{
    "price": 6.49,
    "stock": 60
}

###
DELETE http://localhost:3000/api/products/696e7794fbab4b8cfd05c370

### cart test
GET http://localhost:3000/api/cart/

###
POST http://localhost:3000/api/cart/items
Content-Type: application/json

{
    "productId": "696e7878dc53bb780fcc29b7",
    "quantity": 5
}

###
DELETE http://localhost:3000/api/cart/696a9c74e65437a9091e146e

### category test
GET http://localhost:3000/api/products/categories

###
POST http://localhost:3000/api/products/categories
Content-Type: application/json

{
    "name": "Chocolate",
    "description": "Tasty chocolate candies"
}

###
PUT http://localhost:3000/api/products/categories/696e7268a620c20e72c2b998
Content-Type: application/json

{
    "description": "Delicious gummy candies"
}

###
DELETE http://localhost:3000/api/products/categories/696e7268a620c20e72c2b998

###
GET http://localhost:3000/api/products?category=CHOCOLATE